version: '2'

services:
  apache:
    build: .
    ports:
      - 80:80
    volumes:
      - ".:/var/www/html:rw"

  mysql:
   image: mysql
   ports:
      - "3306:3306"
   environment:
     MYSQL_ROOT_PASSWORD: rootpassword
     MYSQL_DATABASE: redaxo
     MYSQL_USER: user
     MYSQL_PASSWORD: password
