version: '2'

services:
  apache:
    image: bitnami/apache:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/app

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: redaxo
      MYSQL_USER: user
      MYSQL_PASSWORD: password
